name: c

on:
  workflow_dispatch:

jobs:
  fetch_and_send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run new_fetch_data.py
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          REFERER: ${{ secrets.REFERER }}
          ORIGIN: ${{ secrets.ORIGIN }}
          ONE: ${{ secrets.ONE }}
          THREE: ${{ secrets.THREE }}
          FOUR: ${{ secrets.FOUR }}
        run: python new_fetch_data.py


      - name: Send to Discord
        run: python send_to_dis.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Trigger Workflow D via GitHub API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/robot4black/Counts/actions/workflows/d.yaml/dispatches \
            -d '{"ref":"main"}'

      - name: Send to Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python send_to_notion.py       
        
